fix: section header ui
rintoj/native-x-list pull request #7
Opened 2021-09-07 10:37 UTC by rushikeshakhare

2021-09-13 07:31 UTC, Artemnsk reviewed
The rest looks fine, no regressions.

2021-09-13 07:31 UTC, Artemnsk commented on src/list.tsx
> -        <View style={styles.header}>
Remove `header` from `styles` then.

2021-09-14 18:51 UTC, rintoj requested changes

2021-09-14 18:51 UTC, rintoj commented on src/list.tsx
> +  stickySectionHeadersEnabled = false,
Don't make it `false` by default.

2021-09-14 19:31 UTC, rintoj approved these changes

2021-09-14 19:31 UTC, merged